# Generated by Django 3.2.7 on 2022-03-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220213_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='is_vendor',
            field=models.BooleanField(default=False, verbose_name='is vendor'),
        ),
    ]
