# Generated by Django 3.2.8 on 2022-01-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_media',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
