# Generated by Django 3.2.7 on 2022-03-03 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_alter_product_category'),
        ('account', '0005_remove_emailaccount_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='commerce.category', verbose_name='category'),
        ),
    ]
