# Generated by Django 3.2.8 on 2022-01-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_social_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social_media',
        ),
        migrations.AddField(
            model_name='user',
            name='let_say',
            field=models.CharField(default='', max_length=120),
        ),
    ]
