# Generated by Django 3.2.8 on 2022-01-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220118_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='let_say',
        ),
    ]
