# Generated by Django 3.2.8 on 2022-01-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
