# Generated by Django 3.2.8 on 2022-01-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='phone_number',
        ),
    ]
