# Generated by Django 4.0.1 on 2022-01-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_vendor_email_vendor_name_vendor_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='phone_number',
        ),
    ]
