# Generated by Django 4.0.1 on 2022-01-20 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_vendor_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='social_media',
        ),
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
