# Generated by Django 3.2.8 on 2022-01-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_blocked',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='customer status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=False, verbose_name='vendor status'),
        ),
    ]
