# Generated by Django 3.2.8 on 2022-01-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20220126_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='store_name',
            field=models.CharField(default='', max_length=255, verbose_name='store name'),
        ),
    ]
