# Generated by Django 3.2.7 on 2022-02-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_alter_product_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
    ]
