# Generated by Django 3.2.8 on 2022-01-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_vendor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='social_media',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='social media'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(default=None, max_length=14, verbose_name='phone number'),
        ),
    ]
