# Generated by Django 3.2.8 on 2022-01-18 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_vendor'),
        ('commerce', '0003_auto_20220117_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='account.vendor', verbose_name='vendor'),
        ),
        migrations.AlterField(
            model_name='vendorrating',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vendor'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
