# Generated by Django 3.2.7 on 2022-02-07 19:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
