# Generated by Django 3.2.8 on 2022-01-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_auto_20220118_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Order Status', 'verbose_name_plural': 'Order Statuses'},
        ),
    ]
