# Generated by Django 4.0.1 on 2022-01-19 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_vendor_phone_number'),
        ('commerce', '0006_vendor_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='account.vendor', verbose_name='vendor'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
