# Generated by Django 3.2.7 on 2022-02-08 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='qty'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True, verbose_name='slug'),
        ),
    ]
