# Generated by Django 3.2.7 on 2022-02-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_auto_20220208_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='shipping'),
        ),
    ]
