# Generated by Django 3.2.7 on 2022-02-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_auto_20220208_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True, verbose_name='total'),
        ),
    ]
