# Generated by Django 4.0.1 on 2022-01-20 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_vendor_user_customer'),
        ('commerce', '0011_alter_vendorrating_user_alter_vendorrating_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.vendor', verbose_name='vendor'),
        ),
    ]
