# Generated by Django 3.2.7 on 2022-02-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='qty'),
        ),
    ]
