# Generated by Django 3.2.7 on 2022-03-01 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_auto_20220210_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
