# Generated by Django 3.2.8 on 2022-01-21 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_vendor_user_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0014_alter_productrating_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rating', to='commerce.product'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorrating',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_rating', to='account.vendor'),
        ),
    ]
