# Generated by Django 3.2.7 on 2022-03-01 23:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True, verbose_name='slug'),
        ),
    ]
