# Generated by Django 3.2.8 on 2022-01-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
