# Generated by Django 3.2.8 on 2022-01-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0027_auto_20220124_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
