# Generated by Django 3.2.8 on 2022-01-27 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0029_auto_20220127_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
