# Generated by Django 3.2.8 on 2022-01-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0033_alter_productrating_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='commerce.productrating', verbose_name='product rating'),
        ),
    ]
