# Generated by Django 3.2.8 on 2022-01-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0035_auto_20220127_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='product',
        ),
    ]
