# Generated by Django 3.2.8 on 2022-01-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0036_remove_productrating_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='commerce.product'),
        ),
    ]
