# Generated by Django 3.2.8 on 2022-01-27 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0037_productrating_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='ProductRating',
        ),
    ]
