# Generated by Django 3.2.8 on 2022-01-27 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0039_auto_20220127_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='user',
        ),
        migrations.AddField(
            model_name='productrating',
            name='user',
            field=models.ManyToManyField(related_name='product_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
