# Generated by Django 3.2.8 on 2022-01-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0040_auto_20220127_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product_rating',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='commerce.ProductRating', verbose_name='product rating'),
        ),
    ]
