# Generated by Django 3.2.8 on 2022-01-27 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0043_alter_productrating_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorrating',
            name='rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
