# Generated by Django 3.2.8 on 2022-01-27 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0046_alter_productrating_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorrating',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
