# Generated by Django 3.2.8 on 2022-01-27 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0049_alter_vendorrating_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='rate',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
