# Generated by Django 3.2.8 on 2022-01-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0052_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
        migrations.DeleteModel(
            name='An',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
