# Generated by Django 3.2.8 on 2022-02-04 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0053_auto_20220127_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorrating',
            name='user',
        ),
        migrations.AddField(
            model_name='vendorrating',
            name='user',
            field=models.ManyToManyField(related_name='vendor_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
