POST localhost:8000/api/auth/signup
Content-Type: application/json
Accept: application/json

{
  "first_name": "new",
  "last_name": "user",
  "email": "user111@example.com",
  "password1": "string!!@@",
  "password2": "string!!@@"
}